In [32]:
from get_data import get_data

X, y = get_data()
#y = y.where(X.reviewText.str.contains(r'[a-zA-Z]'))
#X = X.where(X.reviewText.str.contains(r'[a-zA-Z]'))

In [43]:
from random import sample
import re
ranges = [10, 50, 100, 500, 2000]

neg = X[y == 0]
pos = X[y == 1]

for r in ranges:
    text = []
    for label, data in enumerate([neg, pos]):
        idxs = range(len(data))
        idxs = sample(idxs, r//2)
        text += list(data.iloc[idxs].reviewText.str.replace('\n', ' '))

    with open(f'../Data/subsets/n_{r}.txt', 'w') as f:
        for i, t in enumerate(text):
            l = int(i < r//2)
            f.write(f'{l}\t{t}\n')

In [33]:
X.str

AttributeError: 'DataFrame' object has no attribute 'str'

In [41]:
data.iloc[idxs].reviewText.str.replace

In [22]:
df.where(df.reviewText.str.contains(r'[a-zA-Z]'))

,verified,reviewTime,reviewerID,asin,reviewText,summary,unixReviewTime,id
0,True,"09 11, 2013",AC2PL52NKPL29,0001388703,"So creative! Love his music - the words, the ...",Gotta listen to this!,1378857600,0
1,False,"05 14, 2009",A3NVGWKHLULDHR,0001388703,This tape can hardly be understood and it was ...,Shame Shame,1242259200,1
2,True,"05 15, 2015",AZ3T21W6CW0MW,0001388703,Buy the CD. Do not buy the MP3 album. Downlo...,Buy the CD. Do not buy the MP3.,1431648000,2
3,True,"10 3, 2016",A50DSLM71EAVO,0001526146,I love Dallas Holms music and voice! Thank Yo...,Five Stars,1475452800,3
4,False,"12 11, 2014",AKNKAT9XGAFPE,0001527134,Great memories of my early years in Christ,Five Stars,1418256000,4
...,...,...,...,...,...,...,...,...
99995,True,"10 7, 2015",A2M2XF2QJZS7T3,B002POOJN8,Great old song. Love it.,Great,1444176000,99995
99996,False,"12 17, 2012",A1BKW2O4G0DB9A,B002PQXDW4,Daniel Smith has no more command of the bassoo...,Absolute garbage,1355702400,99996
99997,True,"11 4, 2017",A262BLYWUG3729,B002PRF7AO,I'm enjoying her album very much!,Five Stars,1509753600,99997
99998,False,"06 24, 2017",A2O9U4W4O7KQH7,B002PRCQTE,These digital files are corrupted. There are ...,BAD DIGITAL RECORDING - Very sad,1498262400,99998
99999,True,"03 16, 2015",A1KR3JAKSF0QYD,B002PSKFNM,I saw the Tempest live performed by the Minnes...,... the Tempest live performed by the Minnesot...,1426464000,99999

In [21]:
empty.where

Object `pd.DataFrame.where` not found.